using KaedeHikarinCialloTeam.PhiRecorder.Worker.Interop;
using KaedeHikarinCialloTeam.PhiRecorder.Worker.Messaging.Contracts;

namespace KaedeHikarinCialloTeam.PhiRecorder.Worker.Rendering;

public static class RenderConfigMapper
{
    public static PhiRenderConfig ToPhiRenderConfig(this RenderConfigContract contract)
    {
        return new PhiRenderConfig
        {
            Width = contract.Width,
            Height = contract.Height,
            EndingLength = contract.EndingLength,
            RenderLoading = contract.RenderLoading,
            Hires = contract.Hires,
            ChartDebugLine = contract.ChartDebugLine,
            ChartDebugNote = contract.ChartDebugNote,
            ChartRatio = contract.ChartRatio,
            AllGood = contract.AllGood,
            AllBad = contract.AllBad,
            Fps = contract.Fps,
            HardwareAccel = contract.HardwareAccel,
            Hevc = contract.Hevc,
            Mpeg4 = contract.Mpeg4,
            CustomEncoder = contract.CustomEncoder,
            DynamicBitrateControl = contract.DynamicBitrateControl,
            Bitrate = contract.Bitrate,
            AggressiveChart = contract.AggressiveChart,
            AggressiveNote = contract.AggressiveNote,
            AggressiveParticle = contract.AggressiveParticle,
            ChallengeColor = (PhiChallengeColor)contract.ChallengeColor,
            ChallengeRank = contract.ChallengeRank,
            NoteScale = contract.NoteScale,
            Particle = contract.Particle,
            PlayerAvatar = contract.PlayerAvatar,
            PlayerName = contract.PlayerName,
            PlayerRks = contract.PlayerRks,
            SampleCount = contract.SampleCount,
            Fxaa = contract.Fxaa,
            ResourcePackPath = contract.ResourcePackPath,
            Speed = contract.Speed,
            VolumeMusic = contract.VolumeMusic,
            VolumeSfx = contract.VolumeSfx,
            ForceLimit = contract.ForceLimit,
            LimitThreshold = contract.LimitThreshold,
            LoudnessEqualization = contract.LoudnessEqualization,
            AudioMixMode = (PhiAudioMixMode)contract.AudioMixMode,
            Watermark = contract.Watermark,
            Roman = contract.Roman,
            Chinese = contract.Chinese,
            Combo = contract.Combo,
            Difficulty = contract.Difficulty,
            JudgeOffset = contract.JudgeOffset,
            FileNameFormat = contract.FileNameFormat,
            RenderLine = contract.RenderLine,
            RenderLineExtra = contract.RenderLineExtra,
            RenderNote = contract.RenderNote,
            RenderDoubleHint = contract.RenderDoubleHint,
            RenderUiPause = contract.RenderUiPause,
            RenderUiName = contract.RenderUiName,
            RenderUiLevel = contract.RenderUiLevel,
            RenderUiScore = contract.RenderUiScore,
            RenderUiCombo = contract.RenderUiCombo,
            RenderUiBar = contract.RenderUiBar,
            RenderBg = contract.RenderBg,
            RenderBgDim = contract.RenderBgDim,
            PreserveFramebuffer = contract.PreserveFramebuffer,
            RenderExtra = contract.RenderExtra,
            BackgroundBlurriness = contract.BackgroundBlurriness,
            MaxParticles = contract.MaxParticles,
            PlayStartTime = contract.PlayStartTime,
            PlayEndTime = contract.PlayEndTime,
            HasPlayEndTime = contract.HasPlayEndTime,
            Fade = contract.Fade,
            AlphaTint = contract.AlphaTint,
        };
    }
}
